#ifndef DF_GENERATOR_H
#define DF_GENERATOR_H

#include <limits>
#include "basicfxn.h"

namespace DiceForge
{
    typedef double real_t;
    typedef unsigned int uint32_t;
    typedef unsigned long uint64_t;
    
    /* DiceForge::Generator<T> - A generic class for RNGs
    T = datatype of random number generated (depends on RNG) */
    template <typename T>
    class Generator
    {
    /*** Note: These are the only functions to be called by the end-user, no need to be re-implemented for each RNG ***/
    public:
        /* next() [Integer] - Returns a random integer generated by the RNG*/
        T next()
        { 
            return generate(); 
        };
        /* next_in_range(min, max) [Integer] - Returns a random integer in the specified range
        * min = minimum value of random number (inclusive)
        * max = maximum value of random number (inclusive) */
        T next_in_range(T min, T max)
        { 
            return generate() % (max - min + 1) + min;
        };
        /* next_in_crange(min, max) [Real] - Returns a random real number in the specified range
        * min = minimum value of random number
        * max = maximum value of random number */
        real_t next_in_crange(real_t min, real_t max)
        { 
            return (max - min) * generate() / real_t(std::numeric_limits<T>().max()) + min;
        };
        /* next_unit() [Real] - Returns a random real between 0 and 1 */
        real_t next_unit()
        {
            return generate() / real_t(std::numeric_limits<T>().max());
        }
        /* set_seed(Number seed) [Function] - Initializes the RNG with specified seed */
        void reset_seed(T seed)
        { 
            reseed(seed);
        }    
    /*** Note: These are the only functions to be implemented by RNG ***/
    private:
        /* Should return a random number using the RNG's algorithm */
        virtual T generate() = 0;        
        /* Should initialize the seed for the RNG */
        virtual void reseed(T seed) = 0;        
    };
}

#endif