#ifndef DF_GENERATOR_H
#define DF_GENERATOR_H

#include <limits>
#include <cmath>
#include <iostream>

#include "../types.h"

namespace DiceForge
{
    /// @brief DiceForge::Generator<T> - A generic class for RNGs
    /// @tparam T datatype of random number generated (RNG implementation specific)
    /// @note Every RNG implemented in DiceForge is derived from this base class. 
    /// @note the user wishes to write their own RNG it is advisable to use this as the base class for compatibility with other features.
    template <typename T>
    class Generator
    {
    public:
        /// @brief Returns a random integer generated by the RNG
        /// @returns An unsigned integer (32 or 64 bit)
        T next();
        /// @brief Returns a random real between 0 and 1
        /// @returns An floating-point real number (64 bit)
        real_t next_unit();
        /// @brief Returns a random integer in the specified range
        /// @param min minimum value of the random number (inclusive)
        /// @param max maximum value of the random number (inclusive)
        /// @returns An signed integer (64 bit)
        int64_t next_in_range(T min, T max);
        /// @brief Returns a random real number in the specified range
        /// @param min minimum value of the random number
        /// @param max maximum value of the random number
        /// @returns An signed floating-point real number (64 bit)
        real_t next_in_crange(real_t min, real_t max);
        /// @brief Re-initializes the RNG with specified seed
        /// @param seed seed provided for initialization
        void reset_seed(T seed);
    /*** Note: These are the only functions to be implemented by the implemenataion RNG ***/
    private:
        /// @brief Should return a random integer generated by the RNG
        virtual T generate() = 0;        
        /// @brief Should initialize the seed for the RNG
        virtual void reseed(T seed) = 0;        
    };
}

#endif